language: php
php:
  - "7.3"
branches:
  only:
    - master
script:
  - composer install
  - bin/phan --allow-polyfill-parser
  - bin/phpstan analyse src
  - bin/phpmd src text controversial,design,unusedcode
